services:
  db:
    image: postgis/postgis:16-3.4
    container_name: dullnit_postgis_db
    restart: always
    environment:
      POSTGRES_USER: dullnit
      POSTGRES_PASSWORD: dullnit_password
      POSTGRES_DB: dullnit_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dullnit -d dullnit_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
