from app.schemas.auth import (
    UserRegisterRequest,
    UserLoginRequest,
    TokenResponse,
    UserResponse,
)
from app.schemas.common import PaginatedResponse, MessageResponse
from app.schemas.skill import (
    SkillCreate,
    SkillResponse,
    SkillAliasCreate,
    CandidateSkillCreate,
    CandidateSkillResponse,
)
from app.schemas.candidate import (
    CandidateLocationBase,
    CandidateLocationResponse,
    CandidateEducationCreate,
    CandidateEducationResponse,
    CandidateExperienceCreate,
    CandidateExperienceResponse,
    CandidateCertificationCreate,
    CandidateCertificationResponse,
    CandidatePreferredRoleCreate,
    CandidatePreferredRoleResponse,
    CandidateProfileUpdate,
    CandidateProfileResponse,
)
from app.schemas.resume import (
    ResumeExtractionResult,
    ResumeUploadResponse,
    ResumeStatusResponse,
    ResumeExtractionReviewResponse,
    ResumeEditRequest,
    ResumeConfirmRequest,
    ExtractedSkillItem,
    ExtractedEducationItem,
    ExtractedExperienceItem,
    ExtractedCertificationItem,
)
from app.schemas.persona import CandidatePersonaResponse
from app.schemas.search import (
    RecruiterSearchRequest,
    CandidateSearchResult,
    NaturalLanguageSearchRequest,
)

__all__ = [
    "UserRegisterRequest",
    "UserLoginRequest",
    "TokenResponse",
    "UserResponse",
    "PaginatedResponse",
    "MessageResponse",
    "SkillCreate",
    "SkillResponse",
    "SkillAliasCreate",
    "CandidateSkillCreate",
    "CandidateSkillResponse",
    "CandidateLocationBase",
    "CandidateLocationResponse",
    "CandidateEducationCreate",
    "CandidateEducationResponse",
    "CandidateExperienceCreate",
    "CandidateExperienceResponse",
    "CandidateCertificationCreate",
    "CandidateCertificationResponse",
    "CandidatePreferredRoleCreate",
    "CandidatePreferredRoleResponse",
    "CandidateProfileUpdate",
    "CandidateProfileResponse",
    "ResumeExtractionResult",
    "ResumeUploadResponse",
    "ResumeStatusResponse",
    "ResumeExtractionReviewResponse",
    "ResumeEditRequest",
    "ResumeConfirmRequest",
    "ExtractedSkillItem",
    "ExtractedEducationItem",
    "ExtractedExperienceItem",
    "ExtractedCertificationItem",
    "CandidatePersonaResponse",
    "RecruiterSearchRequest",
    "CandidateSearchResult",
    "NaturalLanguageSearchRequest",
]
